### ISSUE TITLE
assertion error during evaluating miracle

### ISSUE THREAD

**Issue by kondo-kj** [oshizo/JapaneseEmbeddingEval#5]
Hi,
I tried to evaluate our own model by using this great repository's methods.
But at evaluating miracle step, assertion error raised at `assert set([corpus["train"][idx]["docid"] for idx in hn_indices]) == set(hn_docids)`
When trying to reproduce a `9_text_embedding-ada-002` notebook, the same error raised.

I think, the cause of this error is docids of an item in the hard negative json and docids extracted from corpus by indices of hard negative json's item are not match.

**Comment by oshizo** [comment]
Thanks for reporting the issue.

As you discussed, that assert statement is to check for inconsistencies between the docid in hard negative and the docid obtained by idx from corpus.
The purpose was to detect any future changes in the miracl repository.

I deleted the miracl huggingface cache and re-downloaded the dataset, then manually re-ran `17_intfloat_multilingual-e5-small.ipynb`, but did not reproduce that error.
I don't currently understand why the problem occurs, but I have created a modified version anyway. It gets the text from the corpus with docid instead of using index, but on my environment it slows down the execution by about 3 minutes.
Could you replace the entire cell where the assertion occurs with this code, run it in your environment, and see if you can reproduce the results?

```
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist


def get_text(corpus_item):
    return corpus_item["title"] + " " + corpus_item["text"]


corpus_dict = {item["docid"]: get_text(item) for item in corpus["train"]}

n_total_pos = 0
n_total_tp = 0

for item in ds:
    # query
    query_emb = model.encode([query_prefix + item["query"]])

    # passages are set(300 hard negatives + positives)
    positive_docids = [pp["docid"] for pp in item["positive_passages"]]
    positive_texts = [get_text(pp) for pp in item["positive_passages"]]
    hn_docids = hn[item["query_id"]]["docids"][:miracle_n_hard_negs]

    # drop hard negatives in positives
    hn_docids = [docid for docid in hn_docids if docid not in positive_docids]

    # search target
    target_docids = positive_docids + hn_docids
    target_texts = positive_texts + [corpus_dict[docid] for docid in hn_docids]

    # embedding
    target_embs = model.encode([passage_prefix + text for text in target_texts])

    # topK
    topk_indices = np.argsort(cdist(query_emb, target_embs, metric="cosine"))[0][
        :miracle_n_recall
    ]

    n_pos = len(positive_docids)
    n_tp = len(
        set(topk_indices) & set(range(len(positive_docids)))
    )  # positives are first indices

    n_total_pos += n_pos
    n_total_tp += n_tp

    # if n_pos > n_tp:
    # print(f"{item['query_id']}:{n_tp}/{n_pos}", end=", ")

miracl_recall = n_total_tp / n_total_pos

n_total_pos, n_total_tp, miracl_recall
```

**Comment by kondo-kj** [comment]
Thank you for the reply and proposing a solution code.

I tried to execute your code and was able to reproduce a score of ada, and now I'll evaluate my own model using the code. Of course, this will add a few minutes to the runtime but that's not a big deal.

You can close this issue.
